// The documentation page's behavior, and only its behavior.
//
// The markup - the rendered markdown, the compiled examples, the table of
// contents, the theme colors - is generated by docs-render.js and injected
// into docs.html by the prerender plugin in vite.config.js, in the dev server
// and in the built page alike. So Markdoc, the compiler and the Lezer
// grammars are not in this bundle, and must not become so: importing
// docs-render.js from here would pull all of it back into the page.
//
// What is left is what markup cannot be: the theme dropdown, smooth scrolling,
// the scroll spy, and the copy buttons.

import { loadTheme, applyTheme, themeNames, themeName } from "./theme.js";
import { setupDropdown, dropdownItem } from "./dropdown.js";

// The prerendered page already carries the stored theme, applied before first
// paint by the inline script the plugin injects. This re-applies it as the
// inline custom properties the rest of the app uses, which is what the theme
// toggle then overwrites.
loadTheme();

// Pairs each prerendered TOC link with the heading it targets. The ids are in
// the markup (docs-render.js assigns them, so an anchor works with JS off),
// which leaves nothing to build here - only the two ends to connect, for the
// scroll spy below.
function tocSections() {
  const toc = document.querySelector("#docs-toc");
  const sections = [];

  for (const link of toc.querySelectorAll("a[href^='#']")) {
    const heading = document.getElementById(decodeURIComponent(link.hash.slice(1)));
    if (heading) sections.push({ heading, link });
  }

  return sections;
}

// Smooth scrolling, as one delegated listener rather than one per link.
// #docs-content scrolls itself (see docs.css), so the default jump would move
// the wrong box; scrollIntoView finds the right scrollport on its own.
function initTocScrolling() {
  document.querySelector("#docs-toc").addEventListener("click", (e) => {
    const link = e.target.closest("a[href^='#']");
    if (!link) return;
    const heading = document.getElementById(decodeURIComponent(link.hash.slice(1)));
    if (!heading) return;
    e.preventDefault();
    heading.scrollIntoView({ behavior: "smooth", block: "start" });
  });
}

// Highlights whichever TOC entry corresponds to the section currently at the
// top of the viewport. `#docs-content` scrolls itself (see docs.css), so the
// "current" heading is the last one whose top has scrolled above a small
// margin - not whatever IntersectionObserver's default viewport root would
// see, which is the outer page and never fires. Positions are read fresh
// each tick with getBoundingClientRect rather than cached via offsetTop,
// since offsetTop is relative to the nearest positioned ancestor, not
// necessarily #docs-content itself.
function initTocScrollSpy(sections) {
  if (sections.length === 0) return;
  const content = document.querySelector("#docs-content");
  const margin = 16;
  let ticking = false;

  function updateActive() {
    ticking = false;
    const contentTop = content.getBoundingClientRect().top;
    let current = sections[0];
    for (const section of sections) {
      const offset = section.heading.getBoundingClientRect().top - contentTop;
      if (offset <= margin) current = section;
      else break;
    }
    for (const section of sections) {
      section.link.classList.toggle("active", section === current);
    }
  }

  content.addEventListener("scroll", () => {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(updateActive);
  }, { passive: true });

  updateActive();
}

// One delegated listener rather than one per button: the headers arrive as
// prerendered markup, so there is no per-button closure to attach at creation
// time anyway. Some headers are <summary> elements (the collapsible IC10
// block), where a click on the button would otherwise also toggle the parent
// <details> open/closed - stopPropagation keeps that native behavior from
// firing.
function initCopyButtons() {
  const content = document.querySelector("#docs-content");

  content.addEventListener("click", (e) => {
    const button = e.target.closest(".copy-button");
    if (!button) return;
    e.preventDefault();
    e.stopPropagation();

    const code = button.closest(".code-block")?.querySelector("pre code");
    if (!code) return;

    navigator.clipboard.writeText(code.textContent).then(() => {
      button.classList.add("copied");
      setTimeout(() => button.classList.remove("copied"), 1200);
    });
  });
}

function initThemeToggle() {
  const themeToggle = document.querySelector("#theme-toggle");
  const themeList = document.querySelector("#theme-list");
  const themeGroup = themeToggle.closest(".dropdown");

  // #theme-list is styled to exactly match #theme-toggle's width. Both use
  // the same monospace font, so sizing the toggle (in `ch`) to the longest
  // theme name + " ▾" guarantees every entry fits without truncating, no
  // matter which theme is currently selected.
  const widestName = Math.max(...themeNames.map(name => name.length));
  themeToggle.style.minWidth = `${widestName + 2}ch`;

  const showTheme = () => { themeToggle.textContent = `${themeName()} ▾`; };

  const menu = setupDropdown(themeToggle, themeList, () => {
    themeList.innerHTML = "";
    const current = themeName();

    for (const name of themeNames) {
      themeList.appendChild(dropdownItem(name, name === current, () => {
        menu.close();
        applyTheme(name);
        showTheme();
      }));
    }
  }, themeGroup);

  showTheme();
}

initTocScrolling();
initTocScrollSpy(tocSections());
initCopyButtons();
initThemeToggle();
