// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,let:8, true:76, false:78, if:44, then:46, elif:50, else:54, end:56}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'hOYQPOOOOQO'#Ca'#CaOhQPO'#CoOOQO'#DP'#DPOOQO'#Cy'#CyOmQPO'#DOQOQPOOO!UQPO'#C_O!ZQPO'#CqO!oQPO'#CpO!ZQPO,59ZOOQO-E6w-E6wO!zQPO,58yO!ZQPO'#CeO!ZQPO'#ChO#wQQO,59]OOQO'#DR'#DROOQO'#Cd'#CdOOQO'#Cz'#CzO$OQPO,59[O!ZQPO'#CtO$ZQPO'#CvOOQO,59[,59[O$UQPO,59[O$iQQO1G.uO!ZQPO1G.eO%SQQO,59POOQO,59S,59SO!ZQPO,59UO!ZQPO,59UO!ZQPO,59UO!ZQPO,59UO!ZQPO,59UO%ZQPO1G.wOOQO-E6x-E6xOOQO1G.v1G.vO%oQPO1G.vO%tQQO,59`OOQO,59b,59bO%{QQO7+$POOQO1G.k1G.kOOQO1G.p1G.pO'aQQO1G.pO'hQQO1G.pO(jQQO1G.pO(qQQO1G.pOOQO7+$c7+$cOOQO7+$b7+$bO%ZQPO1G.zOOQO7+$f7+$f",
  stateData: "(x~OqOSPOS~OSVOfWOtPOorP~OUYO~OSVOfWOtPOorXlrXirXkrX~OtPO~OV`OY]O]^OtPOvaOwaO~OidOkeOlfO~OUiOSRafRaoRatRalRaiRakRa~O]mO_lO`nOaoObpO~OgqO~P#fOidOkeOlsO~OSVOfWOtPOlrP~OScifciocitcilciicikci~P#fOZxO~P#fOSVOfWOtPOirPkrPlrP~Ol!PO~Og!QO~P#fOSRqfRqoRqtRqlRqiRqkRq~P#fO_lO`^ia^ib^ig^iS^if^io^it^iZ^il^ii^ik^i~O]^i~P&fO]mO~P&fO]mO_lO`nOb^ig^iS^if^io^it^iZ^il^ii^ik^i~Oa^i~P'oOaoO~P'oO",
  goto: "$_vPPPwP!OPP!Y!YPP!YP!YPPPPww!gPP!nP!rPP!x#RPPP#X#eP#lZROTeq!QYQOTeq!QQ[Vg`WY]^dilmnopZXOTeq!QTbXcQgXRtcWTOeq!QRZTQcXRrcQUOQveQ!OqR!R!QZSOTeq!QQ_WQhYQj]Qk^QudQwiQylQzmQ{nQ|oR}p",
  nodeNames: "⚠ Comment program Declaration let VariableName Assign Number Bool Parens ParenLeft ParenRight UnaryOp AddOp BinaryOp MulOp CompareOp LogicAnd LogicOr Assignment IfExpr If if then ElseIf elif Else else end",
  maxTerm: 39,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "%q~RkX^!vpq!vqr!{st#Wvw#oxy#zyz$Pz{$U{|$Z}!O$Z!P!Q$U!Q![$`!^!_$s!_!`${!`!a$s!c!}%T#R#S%T#T#o%T#p#q%f#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~!{Oq~Q#OP!_!`#RQ#WO`Q~#]SP~OY#WZ;'S#W;'S;=`#i<%lO#W~#lP;=`<%l#W~#rPvw#u~#zOa~~$POY~~$UOZ~~$ZO_~~$`O]~~$eQV~!O!P$k!Q![$`~$pPV~!Q![$kQ$xP`Q!_!`#RR%QPUP!_!`#R~%YSt~!Q![%T!c!}%T#R#S%T#T#o%T~%iP#p#q%l~%qOb~",
  tokenizers: [0, 1],
  topRules: {"program":[0,2]},
  specialized: [{term: 36, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
