// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  program = 2,
  Declaration = 3,
  _let = 4,
  VariableName = 5,
  Assign = 6,
  Number = 7,
  Parens = 8,
  ParenLeft = 9,
  ParenRight = 10,
  UnaryOp = 11,
  AddOp = 12,
  BinaryOp = 13,
  MulOp = 14,
  Assignment = 15
