// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,let:8}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UOYQPOOOOQO'#Ca'#CaOeQPO'#CkOOQO'#Cq'#CqOOQO'#Cl'#ClOjQPO'#CpQOQPOOOuQPO'#C_OzQPO,59VOOQO-E6j-E6jO!YQPO,58yOzQPO'#CdOzQPO'#CgO!hQPO1G.qOOQO'#Cs'#CsOzQPO1G.eO!yQPO,59OOOQO,59R,59ROzQPO,59TOzQPO,59TO#UQPO7+$POOQO1G.j1G.jOOQO1G.o1G.oO#gQPO1G.o",
  stateData: "#{~OcOSPOS~OSVOfPOadP~OUWO~OSVOfPOadX~OfPO~OV^OXZO[[OfPO~OU_OSRaaRafRa~O[cO^bOS_ia_if_i~OYeO[cO^bO~O[cO^bOSRqaRqfRq~O^bOS]i[]ia]if]iY]i~O",
  goto: "!mhPPPiPmPPtPPtPtPi|PPP!S!VP!ZTROTSQOTQYV]^WZ[_bcQTORXTRUOTSOTQ]WQ`ZQa[Qd_QfbRgc",
  nodeNames: "⚠ Comment program Declaration let VariableName Assign Number Parens ParenLeft ParenRight UnaryOp AddOp BinaryOp MulOp Assignment",
  maxTerm: 23,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "$d~RfX^!gpq!gst!lxy#Tyz#Yz{#_{|#d}!O#d!P!Q#_!Q![#i!_!`#|!c!}$R#R#S$R#T#o$R#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lOc~~!qSP~OY!lZ;'S!l;'S;=`!}<%lO!l~#QP;=`<%l!l~#YOX~~#_OY~~#dO^~~#iO[~~#nQV~!O!P#t!Q![#i~#yPV~!Q![#t~$ROU~~$WSf~!Q![$R!c!}$R#R#S$R#T#o$R",
  tokenizers: [0],
  topRules: {"program":[0,2]},
  specialized: [{term: 22, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
