// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  program = 2,
  Instruction = 3,
  InstructionName = 4,
  VariableName = 5,
  Number = 6,
  String = 7,
  FunctionCall = 8,
  FunctionName = 9,
  ParenLeft = 10,
  ParenRight = 11,
  Device = 12,
  Register = 13,
  Label = 14,
  LabelName = 15,
  Colon = 16
