// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,HASH:56, d0:58, d1:60, d2:62, d3:64, d4:66, d5:68, db:70, r0:72, r1:74, r2:76, r3:78, r4:80, r5:82, r6:84, r7:86, r8:88, r9:90, r10:92, r11:94, r12:96, r13:98, r14:100, r15:102, r16:104, r17:106, sp:108, ra:110}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WOYQPOOOOQO'#Cm'#CmOYQPO'#CsOeQPO'#C`O#qQPO'#CdO%yQPO'#C_O&TQPO'#CjOOQO'#Cu'#CuO&YQPO'#CsQOQPOOOOQO'#Ce'#CeOOQO-E6k-E6kO&bQPO,59_O&jQPO,59OOOQO'#Ca'#CaOOQO'#Cw'#CwOOQO'#Cn'#CnO&oQPO,58yOOQO'#Ch'#ChOOQO'#Ci'#CiOOQO,59U,59UO&yQPO,59_O&bQPO,59_O'XQPO1G.yO'gQPO1G.yO'oQPO1G.jOOQO-E6l-E6lOOQO,59Z,59ZOOQO-E6m-E6mO'tQPO7+$eOOQO7+$U7+$UPYQPO'#Cm",
  stateData: "(S~OfOSPOS~OhPOjROlYO~OUSXVSX`_XdSXhSXjSXlSXmSXnSXoSXpSXqSXrSXsSXtSXuSXvSXwSXxSXySXzSX{SX|SX}SX!OSX!PSX!QSX!RSX!SSX!TSX!USX!VSX!WSX!XSX~OY]O~OU_OV_Oj^OlYOmbOnbOobOpbOqbOrbOsbOtcOucOvcOwcOxcOycOzcO{cO|cO}cO!OcO!PcO!QcO!RcO!ScO!TcO!UcO!VcO!WcO!XcO~OdRXhRX~P#vO`dO~OhPOdgX~OhPOdga~OViO~OdRahRa~P#vOhPOjROlYOdga~OhPOjROlYOdgi~OhPOdgi~OZnO~OhPOjROlYOdgq~O",
  goto: "#zlPPPmu}PP!R!_PP}}m!iP!q#V#]PPP#gP#jP#v]VOQegmo]TOQegmoT_Ta[VOQegmoT_TaaSOQTaegmo]UOQegmoQQOYZQegmoQeWSg[fRmhQaTRjaQfWQh[TlfhRXOQWOQ[QXkegmoT`Ta",
  nodeNames: "⚠ Comment program Instruction InstructionName VariableName Number String FunctionCall FunctionName ParenLeft ParenRight Device Register Label LabelName Colon",
  maxTerm: 55,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%i~R]XYzYZ!Y]^zpqzrs!_st#{xy$dyz$i!Q![$n![!]%R!c!}%W#R#S%W#T#o%W~!PRf~XYz]^zpqz~!_Oh~~!bVOr!_rs!ws#O!_#O#P!|#P;'S!_;'S;=`#u<%lO!_~!|OV~~#PRO;'S!_;'S;=`#Y;=`O!_~#]WOr!_rs!ws#O!_#O#P!|#P;'S!_;'S;=`#u;=`<%l!_<%lO!_~#xP;=`<%l!_~$QSP~OY#{Z;'S#{;'S;=`$^<%lO#{~$aP;=`<%l#{~$iOY~~$nOZ~~$sQU~!O!P$y!Q![$n~%OPU~!Q![$y~%WO`~~%]Sj~!Q![%W!c!}%W#R#S%W#T#o%W",
  tokenizers: [0],
  topRules: {"program":[0,2]},
  specialized: [{term: 26, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
