// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,HASH:62, d0:64, d1:66, d2:68, d3:70, d4:72, d5:74, db:76, r0:78, r1:80, r2:82, r3:84, r4:86, r5:88, r6:90, r7:92, r8:94, r9:96, r10:98, r11:100, r12:102, r13:104, r14:106, r15:108, r16:110, r17:112, sp:114, ra:116}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pOYQPOOOOQO'#Cp'#CpOYQPO'#CvOeQPO'#C`O#qQPO'#CdO%yQPO'#C_O&TQPO'#CnOOQO'#Cx'#CxO&YQPO'#CvQOQPOOOOQO'#Ce'#CeOOQO-E6n-E6nO&bQPO,59bO&jQPO,59OOOQO'#Ca'#CaO&oQPO'#ChOOQO'#Cz'#CzOOQO'#Cq'#CqO({QPO,58yOOQO'#Ci'#CiOOQO'#Cm'#CmOOQO,59Y,59YO)VQPO,59bO&bQPO,59bO)eQPO1G.|O)sQPO1G.|O){QPO1G.jO*QQQO'#CjOOQO,59S,59SOOQO-E6o-E6oOOQO,59^,59^OOQO-E6p-E6pO*VQPO7+$hOOQO7+$U7+$UOOQO,59U,59UPYQPO'#Cp",
  stateData: "*e~OiOSPOS~OkPOmROoYO~OUSXVSX_cXgSXkSXmSXoSXpSXqSXrSXsSXtSXuSXvSXwSXxSXySXzSX{SX|SX}SX!OSX!PSX!QSX!RSX!SSX!TSX!USX!VSX!WSX!XSX!YSX!ZSX![SX~OY]O~OU`OV`Om^OoYOpcOqcOrcOscOtcOucOvcOwdOxdOydOzdO{dO|dO}dO!OdO!PdO!QdO!RdO!SdO!TdO!UdO!VdO!WdO!XdO!YdO!ZdO![dO~OgRXkRX~P#vO_eO~OkPOgjX~OkPOgja~OVjO~O_kOU[XV[Xg[Xk[Xm[Xo[Xp[Xq[Xr[Xs[Xt[Xu[Xv[Xw[Xx[Xy[Xz[X{[X|[X}[X!O[X!P[X!Q[X!R[X!S[X!T[X!U[X!V[X!W[X!X[X!Y[X!Z[X![[X~OgRakRa~P#vOkPOmROoYOgja~OkPOmROoYOgji~OkPOgji~OZqO~O`rO~OkPOmROoYOgjq~O",
  goto: "$UoPPPpx!QPP!U!bPP!Q!l!pPP!Qp!s!{#a#gPPP#qP#tP$Q]VOQfhps]TOQfhpsT`Tb[VOQfhpsT`TbaSOQTbfhpsT_TbRl_]UOQfhpsQQOYZQfhpsQfWSh[gRpiQbTRmbQgWQi[TogiRXOQWOQ[QXnfhpsTaTb",
  nodeNames: "⚠ Comment program Instruction InstructionName VariableName Number String FunctionCall FunctionName ParenLeft ParenRight Device DeviceName Channel Colon Integer Register Label LabelName",
  maxTerm: 58,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%k~R]XYzYZ!Y]^zpqzrs!_st#{xy$dyz$i!Q![$n![!]%T!c!}%Y#R#S%Y#T#o%Y~!PRi~XYz]^zpqz~!_Ok~~!bVOr!_rs!ws#O!_#O#P!|#P;'S!_;'S;=`#u<%lO!_~!|OV~~#PRO;'S!_;'S;=`#Y;=`O!_~#]WOr!_rs!ws#O!_#O#P!|#P;'S!_;'S;=`#u;=`<%l!_<%lO!_~#xP;=`<%l!_~$QSP~OY#{Z;'S#{;'S;=`$^<%lO#{~$aP;=`<%l#{~$iOY~~$nOZ~R$uQ`QUP!O!P${!Q![$nP%QPUP!Q![${~%YO_~~%_Sm~!Q![%Y!c!}%Y#R#S%Y#T#o%Y",
  tokenizers: [0, 1],
  topRules: {"program":[0,2]},
  specialized: [{term: 29, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
