// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,HASH:70, d0:72, d1:74, d2:76, d3:78, d4:80, d5:82, db:84, r0:88, r1:90, r2:92, r3:94, r4:96, r5:98, r6:100, r7:102, r8:104, r9:106, r10:108, r11:110, r12:112, r13:114, r14:116, r15:118, r16:120, r17:122, sp:124, ra:126}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&fOYQPOOOOQO'#Ct'#CtOYQPO'#CzOeQPO'#C`O#tQPO'#CdO&PQPO'#C_O&ZQPO'#CrOOQO'#C|'#C|O&`QPO'#CzQOQPOOOOQO'#Ce'#CeOOQO-E6r-E6rO&hQPO,59fO&pQPO,59OOOQO'#Ca'#CaO&uQPO'#ChO)XQPO'#DXO+hQPO'#CmO#yQPO'#CpOOQO'#DO'#DOOOQO'#Cu'#CuO+mQPO,58yOOQO'#Ci'#CiOOQO'#Co'#CoOOQO,59^,59^O+wQPO,59fO&hQPO,59fO,VQPO1G/QO,eQPO1G/QO,mQPO1G.jO,rQQO'#CjOOQO,59S,59SO,wQPO,59XOOQO,59[,59[OOQO-E6s-E6sOOQO,59b,59bOOQO-E6t-E6tO,|QPO7+$lOOQO7+$U7+$UOOQO,59U,59UOOQO1G.s1G.sPYQPO'#Ct",
  stateData: "-[~OmOSPOS~OoPOqROsYO~OUSXVSX_gXeSXkSXoSXqSXsSXtSXuSXvSXwSXxSXySXzSX|SX}SX!OSX!PSX!QSX!RSX!SSX!TSX!USX!VSX!WSX!XSX!YSX!ZSX![SX!]SX!^SX!_SX!`SX!aSX~OY]O~OUcOVcOebOq^OsYOtfOufOvfOwfOxfOyfOzfO|gO}gO!OgO!PgO!QgO!RgO!SgO!TgO!UgO!VgO!WgO!XgO!YgO!ZgO![gO!]gO!^gO!_gO!`gO!agO~OkRXoRX~P#yO_hO~OoPOknX~OoPOkna~OVmO~O_nOU[XV[Xb{Xe[Xk[Xo[Xq[Xs[Xt[Xu[Xv[Xw[Xx[Xy[Xz[X|[X}[X!O[X!P[X!Q[X!R[X!S[X!T[X!U[X!V[X!W[X!X[X!Y[X!Z[X![[X!][X!^[X!_[X!`[X!a[X~OUrXVrXb{XerXkrXorXqrXsrXtrXurXvrXwrXxrXyrXzrX|rX}rX!OrX!PrX!QrX!RrX!SrX!TrX!UrX!VrX!WrX!XrX!YrX!ZrX![rX!]rX!^rX!_rX!`rX!arX~ObpO~OkRaoRa~P#yOoPOqROsYOkna~OoPOqROsYOkni~OoPOkni~OZvO~O`wO~Oq^O~OoPOqROsYOknq~O",
  goto: "$r|PPP}!V!_PP!g!tPP!o#P#UPP!oP!o!oP}#X#a#u#{PPP$VP$YP$fPPPPPPPP$m]VOQikuy]TOQikuyU`TbeRxp[VOQikuyVcTbecSOQTbeikuyV_TbeRo_]UOQikuyQQOYZQikuyQiWSk[jRulQeTRreQjWQl[TtjlRXOQWOQ[QXsikuySdTeRqbVaTbe",
  nodeNames: "⚠ Comment program Instruction InstructionName VariableName Number String FunctionCall FunctionName ParenLeft ParenRight Device DeviceName Channel Colon Integer DeviceProperty Dot Register UnaryOp AddOp Label LabelName",
  maxTerm: 63,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "&O~R`XY!TYZ!c]^!Tpq!Trs!hst$Uxy$myz$r{|$w}!O$w!O!P$|!Q![%R![!]%h!c!}%m#R#S%m#T#o%m~!YRm~XY!T]^!Tpq!T~!hOo~~!kVOr!hrs#Qs#O!h#O#P#V#P;'S!h;'S;=`$O<%lO!h~#VOV~~#YRO;'S!h;'S;=`#c;=`O!h~#fWOr!hrs#Qs#O!h#O#P#V#P;'S!h;'S;=`$O;=`<%l!h<%lO!h~$RP;=`<%l!h~$ZSP~OY$UZ;'S$U;'S;=`$g<%lO$U~$jP;=`<%l$U~$rOY~~$wOZ~~$|Oe~~%ROb~R%YQ`QUP!O!P%`!Q![%RP%ePUP!Q![%`~%mO_~~%rSq~!Q![%m!c!}%m#R#S%m#T#o%m",
  tokenizers: [0, 1],
  topRules: {"program":[0,2]},
  specialized: [{term: 33, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
